"use client";
import { useEffect,useMemo,useState } from "react";
type Pick={id:string;name:string;odds:number;event:string;eventId:string;market?:string};
function read():Pick[]{try{return JSON.parse(localStorage.getItem("sportsbook_betslip")||"[]")}catch{return[]}}
export default function Betslip(){const [picks,setPicks]=useState<Pick[]>([]);const [stake,setStake]=useState(1000);const [balance,setBalance]=useState<number|null>(null);const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{const sync=()=>setPicks(read());sync();window.addEventListener("storage",sync);window.addEventListener("sportsbook-betslip-change",sync);return()=>{window.removeEventListener("storage",sync);window.removeEventListener("sportsbook-betslip-change",sync)}},[]);
 useEffect(()=>{fetch("/api/wallet",{cache:"no-store"}).then(r=>r.json()).then(j=>setBalance(j.authenticated?Number(j.balance_minor):null)).catch(()=>{})},[]);
 const total=useMemo(()=>picks.reduce((a,p)=>a*p.odds,1),[picks]);const potential=Math.floor(stake*total);
 function remove(id:string){const next=picks.filter(p=>p.id!==id);localStorage.setItem("sportsbook_betslip",JSON.stringify(next));setPicks(next)}
 function clear(){localStorage.removeItem("sportsbook_betslip");setPicks([])}
 async function place(){if(picks.length!==1){setMsg("Select one outcome at a time. Multi-selection accumulator placement is not enabled yet.");return}if(stake<1||!Number.isSafeInteger(stake)){setMsg("Enter a valid whole-number stake.");return}if(balance!==null&&stake>balance){setMsg("Stake is above your available balance.");return}setBusy(true);setMsg("Checking account, quote and limits…");try{const r=await fetch("/api/bets/place",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({selectionId:picks[0].id,stakeMinor:stake,idempotencyKey:crypto.randomUUID()})});const j=await r.json();if(j.bet_id){setMsg("Bet accepted. Opening My Bets…");localStorage.removeItem("sportsbook_betslip");setPicks([]);setTimeout(()=>location.href="/my-bets",700)}else setMsg("Unable to place: "+(j.error||"Request failed"));}catch{setMsg("Network error. Please try again")}finally{setBusy(false)}}
 return <main className="min-h-screen p-5"><div className="mx-auto max-w-3xl"><div className="flex items-center justify-between"><a href="/" className="text-sm text-slate-400">← Sportsbook</a><a href="/account" className="text-sm text-slate-400">Account</a></div><h1 className="mt-6 text-3xl font-bold">Bet Slip</h1>{picks.length===0?<div className="panel mt-5"><div className="text-lg font-bold">Your bet slip is empty</div><p className="mt-2 text-sm text-slate-400">Choose an outcome from a sport or event market.</p><a href="/" className="primary mt-5 inline-flex">Browse sports</a></div>:<div className="mt-5 space-y-3">{picks.map(p=><div key={p.id} className="panel"><div className="flex justify-between gap-3"><div><div className="text-xs text-slate-500">{p.event}{p.market&&" • "+p.market}</div><div className="mt-1 font-semibold">{p.name}</div></div><div className="text-right"><b>{p.odds.toFixed(2)}</b><button onClick={()=>remove(p.id)} className="mt-2 block text-xs text-slate-500 hover:text-white">Remove</button></div></div></div>)}<div className="panel"><div className="flex items-center justify-between"><span className="text-sm text-slate-400">Available balance</span><b>{balance===null?"Sign in":balance.toLocaleString()}</b></div><label className="mt-5 block text-sm text-slate-400">Stake (minor units)</label><input className="field mt-2" type="number" min="1" step="1" value={stake} onChange={e=>setStake(Number(e.target.value))}/><div className="mt-4 flex justify-between"><span>Total odds</span><b>{total.toFixed(2)}</b></div><div className="mt-2 flex justify-between"><span>Potential return</span><b>{potential.toLocaleString()}</b></div><button disabled={busy} className="primary mt-5 w-full" onClick={place}>{busy?"Placing…":"Place bet"}</button><button disabled={busy} onClick={clear} className="mt-3 w-full text-sm text-slate-500 hover:text-white">Clear slip</button>{msg&&<p className="mt-3 text-sm text-slate-300">{msg}</p>}</div></div>}</div></main>}