import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
export default async function MyBets(){
 const s=await createClient(); const {data:{user}}=await s.auth.getUser(); let bets:any[]=[];
 if(user){const r=await s.schema("sportsbook").from("bets").select("id,status,bet_type,stake_minor,potential_payout_minor,odds_snapshot,placed_at,bet_legs(market_name,selection_name,outcome,odds_snapshot)").eq("user_id",user.id).order("placed_at",{ascending:false});bets=r.data??[]}
 return <main className="min-h-screen px-4 pb-28 pt-5 sm:px-6"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><Link href="/" className="text-sm font-semibold text-slate-400 hover:text-white">← Sportsbook</Link><Link href="/wallet" className="text-sm font-semibold text-slate-400 hover:text-white">Wallet →</Link></div><div className="mt-7"><div className="text-[10px] font-black tracking-[.3em] text-emerald-400/80">ACCOUNT ACTIVITY</div><h1 className="mt-1 text-3xl font-black">My Bets</h1></div>
 {!user?<div className="panel mt-6">Please <Link className="underline" href="/login">sign in</Link> to view your bets.</div>:bets.length===0?<div className="panel mt-6"><div className="text-lg font-bold">No bets yet</div><p className="mt-2 text-sm text-slate-500">Your accepted bets will appear here.</p><Link className="primary mt-5 inline-flex" href="/">Browse events</Link></div>:
 <div className="mt-6 space-y-4">{bets.map(b=><article className="panel" key={b.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="rounded-full border border-white/10 bg-white/[.03] px-2.5 py-1 text-[10px] font-black uppercase tracking-wider">{b.status}</span><span className="ml-2 text-xs text-slate-600">{b.bet_type||"single"}</span></div><time className="text-xs text-slate-500">{new Date(b.placed_at).toLocaleString()}</time></div><div className="mt-4 overflow-hidden rounded-xl border border-white/8">{(b.bet_legs||[]).map((l:any,i:number)=><div key={l.selection_name+"-"+i} className="flex items-center justify-between gap-4 border-b border-white/8 px-4 py-3 last:border-b-0"><div className="min-w-0"><div className="truncate text-sm font-bold">{l.selection_name}</div><div className="mt-1 text-xs text-slate-500">{l.market_name}{l.outcome?" • "+l.outcome:""}</div></div><b className="shrink-0 text-emerald-300">{Number(l.odds_snapshot||b.odds_snapshot||0).toFixed(2)}</b></div>)}</div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/8 bg-black/15 p-3"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-600">Stake</div><div className="mt-1 font-black">{Number(b.stake_minor).toLocaleString()}</div></div><div className="rounded-xl border border-white/8 bg-black/15 p-3"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-600">Potential return</div><div className="mt-1 font-black text-emerald-300">{Number(b.potential_payout_minor).toLocaleString()}</div></div></div></article>)}</div>}
 </div></main>}
