"use client";
import { useEffect,useMemo,useState } from "react";

const footballGroups=["All","Match Result","Double Chance","Goals","Both Teams to Score","Correct Score","Team Goals","Corners","Cards","Player Shots","Shots on Target","Goalscorers","Free Kicks","Throw Ins","Goal Kicks","Asian Handicap","First Half","Extra Time","In-Play"];
const cricketGroups=["All","Match Winner","Innings Runs","Team Runs","Boundaries","4s / 6s","Odd / Even","Player Runs","Player Wickets","Next Over","Next 5 Balls","Series / Tournament"];

function addToSlip(selection:any,event:any,market:any){
 const q=selection.odds_quotes?.[0]; if(!q||selection.status!=="open"||market.status!=="open") return;
 let old:any[]=[];try{old=JSON.parse(localStorage.getItem("sportsbook_betslip")||"[]")}catch{}
 old=old.filter(x=>x.eventId!==event.id);
 old.push({id:selection.id,name:selection.name,odds:Number(q.decimal_odds),event:event.name,eventId:event.id,market:market.name});
 localStorage.setItem("sportsbook_betslip",JSON.stringify(old));
 window.dispatchEvent(new Event("sportsbook-betslip-change"));
}

function Stat({label,value}:{label:string,value:any}){return <div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-xs uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 text-lg font-bold">{value??"—"}</div></div>}

export default function EventPage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState("");const [event,setEvent]=useState<any>(null);const [live,setLive]=useState<any>(null);const [tab,setTab]=useState<"markets"|"live">("markets");const [group,setGroup]=useState("All");const [notice,setNotice]=useState("");
 useEffect(()=>{void params.then(p=>setId(p.id))},[params]);
 useEffect(()=>{if(!id)return;fetch("/api/events/"+id,{cache:"no-store"}).then(r=>r.json()).then(j=>setEvent(j.event||null)).catch(()=>setNotice("Unable to load event"));},[id]);
 useEffect(()=>{if(!id)return;let alive=true;const load=()=>fetch("/api/events/"+id+"/live",{cache:"no-store"}).then(r=>r.json()).then(j=>{if(alive)setLive(j.live)}).catch(()=>{});void load();const t=window.setInterval(load,10000);return()=>{alive=false;window.clearInterval(t)}},[id]);
 const sport=String(event?.competitions?.sports?.name||"").toLowerCase();const groups=useMemo(()=>sport.includes("cricket")?cricketGroups:footballGroups,[sport]);
 const visibleMarkets=useMemo(()=>{const ms=event?.markets||[];if(group==="All")return ms;const needle=group.toLowerCase();return ms.filter((m:any)=>m.name.toLowerCase().includes(needle)||needle.includes(m.name.toLowerCase())||((needle==="match result")&&/winner|result/i.test(m.name)));},[event,group]);
 function pick(m:any,p:any){addToSlip(p,event,m);setNotice("Selection added to bet slip");window.setTimeout(()=>setNotice(""),1800)}
 if(!id)return <main className="min-h-screen p-5"><div className="mx-auto max-w-6xl">Loading…</div></main>;
 return <main className="min-h-screen bg-slate-950"><header className="sticky top-0 z-30 border-b border-white/10 bg-slate-950/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href="/" className="font-bold">SPORTSBOOK</a><div className="flex gap-2"><a href="/betslip" className="rounded-xl border border-white/10 px-3 py-2 text-sm">Bet Slip</a><a href="/account" className="rounded-xl border border-white/10 px-3 py-2 text-sm">Account</a></div></div></header>
 <div className="mx-auto max-w-6xl px-5 py-5"><a href="/" className="text-sm text-slate-400">← Sports</a>{!event?<div className="panel mt-5">Loading event…</div>:<>
 <section className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-white/[.04]"><div className="p-5 md:p-7"><div className="text-xs uppercase tracking-widest text-slate-500">{event.competitions?.sports?.name} • {event.competitions?.name}</div><h1 className="mt-2 text-2xl font-black md:text-3xl">{event.name}</h1><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="text-center text-lg font-bold">{live?.home_name||"Home"}</div><div className="text-center"><div className="text-4xl font-black">{live?.score?.home??"0"} - {live?.score?.away??"0"}</div>{live?.is_live?<div className="mt-2"><span className="live">LIVE</span> <span className="ml-2 text-sm text-slate-400">{live.clock||live.period||"In play"}</span></div>:<div className="mt-2 text-sm text-slate-400">{new Date(event.starts_at).toLocaleString()}</div>}</div><div className="text-center text-lg font-bold">{live?.away_name||"Away"}</div></div></div><div className="flex border-t border-white/10"><button onClick={()=>setTab("markets")} className={tab==="markets"?"flex-1 border-b-2 border-white px-4 py-3 text-sm font-bold":"flex-1 px-4 py-3 text-sm text-slate-400"}>Markets</button><button onClick={()=>setTab("live")} className={tab==="live"?"flex-1 border-b-2 border-white px-4 py-3 text-sm font-bold":"flex-1 px-4 py-3 text-sm text-slate-400"}>Match Live</button></div></section>
 {tab==="live"?<section className="mt-4 space-y-4"><div className="panel"><div className="flex items-center justify-between"><h2 className="font-bold">Live Match Center</h2><span className="text-xs text-slate-500">{live?.source||"Provider ready"}</span></div><div className="mt-7 text-center"><div className="text-6xl font-black">{live?.score?.home??0} : {live?.score?.away??0}</div><div className="mt-2 text-slate-400">{live?.period||"Waiting for live coverage"} {live?.clock&&"· "+live.clock}</div></div></div><div className="panel"><h2 className="font-bold">Live statistics</h2><div className="mt-4 grid gap-3 grid-cols-2 md:grid-cols-4"><Stat label="Possession" value={live?.stats?.possession||live?.stats?.team?.possession}/><Stat label="Shots" value={live?.stats?.shots||live?.stats?.team?.shots}/><Stat label="Shots on target" value={live?.stats?.shots_on_target||live?.stats?.team?.shots_on_target}/><Stat label="Corners" value={live?.stats?.corners||live?.stats?.team?.corners}/><Stat label="Yellow cards" value={live?.stats?.yellow_cards||live?.stats?.team?.yellow_cards}/><Stat label="Red cards" value={live?.stats?.red_cards||live?.stats?.team?.red_cards}/><Stat label="Fouls" value={live?.stats?.fouls||live?.stats?.team?.fouls}/><Stat label="Source" value={live?.source||"Internal"}/></div><details className="mt-4"><summary className="cursor-pointer text-xs text-slate-500">Provider payload</summary><pre className="mt-3 max-h-64 overflow-auto text-xs text-slate-500">{JSON.stringify(live?.stats||{},null,2)}</pre></details></div></section>
 :<section className="mt-4"><div className="flex gap-2 overflow-x-auto pb-3">{groups.map(g=><button key={g} onClick={()=>setGroup(g)} className={group===g?"tab tab-active":"tab"}>{g}</button>)}</div><div className="space-y-4">{visibleMarkets.length?visibleMarkets.map((m:any)=><div className="panel" key={m.id}><div className="flex items-center justify-between"><h2 className="font-bold">{m.name}</h2><span className="text-xs text-slate-500">{m.status==="open"?"Open":"Suspended"}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{m.selections?.map((p:any)=>{const q=p.odds_quotes?.[0];return <button disabled={!q||p.status!=="open"||m.status!=="open"} onClick={()=>pick(m,p)} className="odd disabled:opacity-40" key={p.id}><span>{p.name}</span><b>{q?Number(q.decimal_odds).toFixed(2):"—"}</b></button>})}</div></div>):<div className="panel"><b>{group}</b><p className="mt-2 text-sm text-slate-400">No supplied selections for this market family on this event.</p></div>}</div></section>}{notice&&<div className="toast">{notice} · <a href="/betslip" className="underline">Open slip</a></div>}</>}</div></main>;
}