"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
type Event={id:string;name:string;starts_at:string;status:string;is_live:boolean;competitions?:{name:string;sports?:{name:string}}};
type LiveData={live?:{is_live?:boolean;score_home?:number;score_away?:number;period?:string;clock?:string;provider?:string}};
export default function LivePage(){
 const [events,setEvents]=useState<Event[]>([]); const [scores,setScores]=useState<Record<string,LiveData>>({}); const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true; const load=async()=>{try{const r=await fetch("/api/events",{cache:"no-store"});const j=await r.json();const next=(j.events||[]).filter((e:Event)=>e.is_live);if(!alive)return;setEvents(next);const results=await Promise.all(next.map(async (e:Event)=>{try{const rr=await fetch("/api/events/"+e.id+"/live",{cache:"no-store"});return [e.id,await rr.json()] as const}catch{return [e.id,{}] as const}}));if(alive)setScores(Object.fromEntries(results));}finally{if(alive)setLoading(false)}};void load();const t=setInterval(load,10000);return()=>{alive=false;clearInterval(t)}},[]);
 return <main className="min-h-screen px-4 pb-28 pt-5 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><Link href="/" className="text-sm font-semibold text-slate-400 hover:text-white">← Sportsbook</Link><span className="live">LIVE CENTER</span></div><div className="mt-7"><div className="text-[10px] font-black tracking-[.3em] text-emerald-400/80">IN-PLAY</div><h1 className="mt-1 text-3xl font-black">Live Matches</h1><p className="mt-2 text-sm text-slate-500">Scores and match state refresh automatically.</p></div>{loading?<div className="panel mt-7">Loading live events…</div>:events.length===0?<div className="panel mt-7"><div className="text-lg font-bold">No live events right now</div><p className="mt-2 text-sm text-slate-400">Covered live events will appear here automatically.</p></div>:<div className="mt-7 grid gap-4 lg:grid-cols-2">{events.map((e:Event)=>{const d=scores[e.id]?.live||{};return <Link href={"/event/"+e.id} key={e.id} className="panel block transition hover:-translate-y-0.5 hover:border-emerald-400/30"><div className="flex items-center justify-between gap-3"><div><span className="live">LIVE</span><span className="ml-2 text-[10px] font-bold uppercase tracking-wider text-slate-600">{e.competitions?.sports?.name}</span></div><span className="text-xs text-slate-500">{d.provider||"live feed"}</span></div><h2 className="mt-4 text-lg font-black">{e.name}</h2><div className="mt-4 flex items-end justify-between rounded-xl border border-white/8 bg-black/20 p-4"><div><div className="text-[10px] font-black tracking-[.18em] text-slate-600">{d.period||"MATCH"}</div><div className="mt-1 text-3xl font-black tabular-nums">{Number(d.score_home??0)} <span className="text-slate-700">—</span> {Number(d.score_away??0)}</div></div><div className="text-right"><div className="text-lg font-black text-emerald-300">{d.clock||"—"}</div><div className="mt-1 text-xs text-slate-500">{e.competitions?.name}</div></div></div><div className="mt-4 flex justify-between text-xs"><span className="text-slate-500">Open match center</span><b className="text-emerald-400">View markets →</b></div></Link>})}</div>}</div></main>}
